### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by IvanIsak2000** [michael7nightingale/English-drf#2]
What? 😨
![image](https://github.com/michael7nightingale/English-drf/assets/79650307/84554879-f038-46fc-8dfa-2c68cae39a3c)
![image](https://github.com/michael7nightingale/English-drf/assets/79650307/8e672c3b-8933-476c-b3a0-ed1e6b5a54af)

**Comment by michael7nightingale** [comment]
I like JS really, it`s just outrageous.
